### ISSUE TITLE
How firebase api can respond to google pub/sub or database events using nest.js

### ISSUE THREAD

**Issue by RezaRahmati** [caiorcferreira/nest-js-firebase#3]
Hey

I have question after integrating to firebase, how it can respond to google pub/sub or other events that firebase functions respond to.

**Comment by caiorcferreira** [comment]
There isn't a standard or best practice in this matter, as I know of.
As the [Realtime Database documentation](https://firebase.google.com/docs/database/extend-with-functions) shows, to respond to events in Cloud Functions you need to write something in this terms:
```js
exports.foo = functions.database.ref('/foo/bar').onWrite(event => { ... })
```
So, a I suggest that instead of passing arrow functions to `onWrite`, you create a class with methods that has the correct type signature (`func(e: Event): any`) and registry this methods for the events you want to listen. As for the registry mechanism, it can be from a simple function where you hard-code the binding to use [Nest custom decorators](https://docs.nestjs.com/custom-decorators) to provide metadata with [Nest executtion context](https://docs.nestjs.com/execution-context) to traverse the modules tree and dinamycally registry the bindings.

**Comment by RezaRahmati** [comment]
Thanks for fast response,  
I still didn't understand the solution
For example in server.ts line 14,15 we have
```
startNestApplication(server);
exports.api = functions.https.onRequest(server);

```
In that case should I add another exports like below as well as the above code ?
```
startNestApplication(server);
exports.api = functions.https.onRequest(server);
exports.foo = functions.database.ref('/foo/bar').onWrite(mydbClassListener.onwrite)
````

Since I am new to nest.js I appreciate if you would add some pesudo code about the class and other stuff

**Comment by Newbie012** [comment]
Hi @RezaRahmati, Did you find a solution?

**Comment by RezaRahmati** [comment]
@Newbie012 yes, please see below code snippet

```
import * as functions from 'firebase-functions';
import * as express from 'express';

import { NestFactory } from '@nestjs/core';
const server: any = express();

const startNestApplication = async (expressInstance: any) => {
    const app = await NestFactory.create(ApplicationModule, expressInstance);
    await app.init();
};

startNestApplication(server);
exports.api = functions.https.onRequest(server);

exports.onWriteSubject = functions.firestore
    .document('subject/{subjectId}')
    .onWrite((change, context) => {
          ... your code here
    });

exports.onCreateUser = functions.auth.user()
    .onCreate(async (user) => {
          ... your code here
    });

```

**Comment by Newbie012** [comment]
@RezaRahmati That's not what I was probably looking for, but I really appreciate your response :)

The issue I'm facing is posted here - https://stackoverflow.com/questions/53307541/firebase-handle-cloud-events-within-nestjs-framework
