### ISSUE TITLE
How should be architecture of micro-services in firebase + nest.js

### ISSUE THREAD

**Issue by RezaRahmati** [caiorcferreira/nest-js-firebase#4]
When integrating nest.js with firebase and publishing there will be just 1 endpoint on firebase called `api`
My question is how should be the architecture of micro-services with firebase + nest.js

Should I create different firebase project with single nest module?
Should I create 1 firebase project with multiple modules?

**Comment by caiorcferreira** [comment]
If you aim to create a truly microservice architecture then, IMHO you should have different Firebase projects, with each service in its own repository as well. But saying that this project would have *a single nest module* is ambiguous since any Nest application must have a single Root Module with any number of underline modules you want.
Also, as you want to develop microservices in Nest I would recommend take a look at the [nest microservice modules documentation](https://docs.nestjs.com/microservices/basics), it has native support for TCP or Redis Pub/Sub as the message transportation ports but can easily be extended to use an HTTP(S) port, whereas I belive that Firebase just support HTTP(S).

**Comment by RezaRahmati** [comment]
Thanks I will take a look
(By single module I meant Root Module + another module for that micro service domain)

**Comment by RezaRahmati** [comment]
What about this way, do you think it's a good way?

- Creating 1 project in firebase
- Creating multiple project with reference to same firebase project
- Each project has it's own modules with different names
For example moudle1
```
startNestApplication(server);
exports.microservice1 = functions.https.onRequest(server);
```

For example moudle2
```
startNestApplication(server);
exports.microservice2 = functions.https.onRequest(server);
```

**Comment by RezaRahmati** [comment]
I tried above solution (that I proposed) it didn't work, in the time of publishing it will delete all existing ones except the one that is publishing
